apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8sdisksinwritesingle
  annotations:
    description: Ensures that maximum 1 disk is allowed to be attached in write mode on VM
spec:
  crd:
    spec:
      names:
        kind: K8sDisksInWriteSingle
      validation:
        # Schema for the `parameters` field
        openAPIV3Schema:
          type: object
          properties:
            diskwritenum:
              description: Number of disks that can be attached to the VM in write mode
              type: integer

  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8sdisksinwritesingle

        violation[{"msg": msg}] {
            input.review.kind.kind == "VirtualMachine"
            numofdisks := 0
            diskwriteval := input.parameters.diskwritenum
            numofdisks := numofdisks + 1 if { !input.review.object.spec.disks[_].readOnly }
            numofdisks > diskwriteval
            msg := sprintf("No. of disks: %v of write type not allowed", [numofdisks])
        }
