apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8sdisksinwritesingle
  annotations:
    description: Ensures that all Disks are attached in Read-only mode on vm
spec:
  crd:
    spec:
      names:
        kind: K8sDisksInWriteSingle
      validation:
        # Schema for the `parameters` field
        openAPIV3Schema:
          type: object
          properties:
            diskwritenum:
              description: Number of disks that can be attached to the VM in write mode
              type: integer

  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8sdisksinwritesingle

        violation[{"msg": msg}] {
            readOnlyRes := input.review.object.spec.disks[_].readOnly
            readOnlyCons := input.parameters.diskwritenum
            diskwritenum <= 1
            msg := sprintf("Disks of readOnly value %v not allowed", [readOnlyRes])
        }
