apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sDisksInWriteSingle
metadata:
  name: require-single-write-disk
spec:
  match:
    kinds:
      - apiGroups: ["vm.cluster.gke.io"]
        kinds: ["VirtualMachine"]
  parameters:
    diskwritenum: 1
