apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sDisksInReadonly
metadata:
  name: require-disks-in-read-only
spec:
  match:
    kinds:
      - apiGroups: ["vm.cluster.gke.io"]
        kinds: ["VirtualMachine"]
  parameters:
    readOnly: true
